# Generated by Django 2.2.6 on 2019-10-19 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mario',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mario_gaming.Character')),
            ],
            bases=('mario_gaming.character',),
        ),
        migrations.CreateModel(
            name='Princess',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mario_gaming.Character')),
            ],
            bases=('mario_gaming.character',),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_size', models.IntegerField(default=0)),
                ('mario', models.ForeignKey(blank=True, on_delete=True, related_name='mario', to='mario_gaming.Mario')),
                ('princess', models.ForeignKey(blank=True, on_delete=True, related_name='princess', to='mario_gaming.Princess')),
            ],
        ),
    ]
