# Generated by Django 2.2.6 on 2019-10-20 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'solution',
            },
        ),
        migrations.CreateModel(
            name='Combinaison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('solution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combinaisons', to='mario_gaming.Solution')),
            ],
            options={
                'db_table': 'combinaison',
            },
        ),
    ]
