# Generated by Django 2.2.6 on 2019-10-20 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mario_gaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='combinaison',
            table=None,
        ),
        migrations.AlterModelTable(
            name='solution',
            table=None,
        ),
    ]
